> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# NumPy


### Introduction 

NumPy, short for Numerical Python, is a Python module used for working with arrays.
It has various defined functions that makes working with arrays incredibly faster and easy to use.

- numpy.array() - creates an array out of a list of values
- numpy.shape(array_name) - shows the number of elements in each dimension of an array.
- numpy.reshape(array_name) - changes the shape of an array. Basically it helps to reshape the dimensions of an array.
- Where(value) - helps to search for a value within an array and returns the index if found.
- multiply(ar1,ar2,ar3....) - conducts element wise multiplication and returns the result.

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [2]:
!pip install jovian --upgrade -q

In [3]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sankhadeepriju/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/sankhadeepriju/numpy-array-operations


'https://jovian.ai/sankhadeepriju/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
# function1 = np.array()
# function2 = np.shape()
# function3 = np.reshape()
# function4 = np.copy()
# function5 = np.multiply()

## Function 1 - np.array()

This function helps us to create array object using NumPy module. The array object created is of type numpy.ndarray

In [6]:
# Example 1 - working
a = [1,2,3,4]
ar1 = np.array(a)
print (ar1)

[1 2 3 4]


The list 'a' containing integers got converted into an array object in the name of ar1 consisting the same values as in the list.

In [7]:
# Example 2 - working
b = ['a','b','v','w']
ar2 = np.array(b)
print (ar2)

['a' 'b' 'v' 'w']


The list 'a' containing string got converted into an array object in the name of ar2 consisting the same values as in the list.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
x = ['a',2,3,c]
ar3 = np.array(x)
print (ar3)

NameError: name 'c' is not defined

The list 'x' has 3 defined literals and 1 undefined literal at index 3 and so the array object couldn't be created.
If the last element would've been written as 'c', NumPy would've created an array of String type.

Carefully use this function to create an array of your required data type keeping in mind the data type of the list of values.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Function 2 - np.shape

This function gives an idea about the dimension of an array, basically the number of elements in each dimension of an array. 

In [9]:
# Example 1 - working
np.shape(ar1)

(4,)

It shows us that the array 'ar1' is a 1D-array with 4 elements in it.

In [10]:
# Example 2 - working
arr1 = np.array([[1,2,4],[3,7,2],[2,4,7],[11,3,15]])
arr1.shape

(4, 3)

It shows us that the array 'arr1' is a 2D-array with 4 rows each having 3 elements in it.
It means first dimension has 4 elements each of which contains 3 elements inside of it, meaning second dimension has 3 elements.

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = np.array([[1,2,2,4],[3,7,2],[2,4,7],[11,3,15]])
arr2.shape

/tmp/ipykernel_37/1943449949.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([[1,2,2,4],[3,7,2],[2,4,7],[11,3,15]])


(4,)

It shows us that the array 'arr2' is a 2D-array with 4 rows each having 3 elements in it, except for the first row.
It means first dimension has 4 elements, in which the first element has 4 elements inside of it and the remaining ones of the first dimension has 3 elements.

Use shape function to understand the dimensions of the array, which is useful to locate elements.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Function 3 - np.reshape()

This function helps to change the dimension of an array, that is to change the arrangements of the data in each dimension and even add or remove dimensions.

In [12]:
# Example 1 - working
arr1.reshape(3,4)

array([[ 1,  2,  4,  3],
       [ 7,  2,  2,  4],
       [ 7, 11,  3, 15]])

Here, we can see that the array arr1 which originally had dimensions 4,3 now has dimension 3,4.
The original arr1 has 12 elements arrange in 4 groups each having 3 elements, but now it's 3 groups with 4 elements each.
arr1 dimension remained the same, 2D.

In [13]:
# Example 2 - working
arr1.reshape(1,12)

array([[ 1,  2,  4,  3,  7,  2,  2,  4,  7, 11,  3, 15]])

Here, you can see that there's only 1 element in the first dimension that has 12 element inside of it.
but, you can also see this same array as just 12 independent elements which is not enclosed within a single element of the first dimension.
Here's the reshape:

In [14]:
arr1.reshape(12)

array([ 1,  2,  4,  3,  7,  2,  2,  4,  7, 11,  3, 15])

See, how the first dimension has no internal dimensions but only 12 elements in it.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
arr1.reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

reshape() of arr1 with 12 elements in total failed because it's not possible to fit 12 elements in a total fitting size of 15 elements.
reshape() works only when the new array dimension with total number of elements match with the former one.

The reshape() function is highly useful to transform matrices/array into your desired shape.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Function 4 - np.copy()

The function searches the array for a given value and returns the index.

In [19]:
# Example 1 - working
x1 = arr1.copy()
x1
# make changes in x1
x1[0,0]=11
print('Copy:\n',x1)
print('Original:\n',arr1)

Copy:
 [[11  2  4]
 [ 3  7  2]
 [ 2  4  7]
 [11  3 15]]
Original:
 [[ 1  2  4]
 [ 3  7  2]
 [ 2  4  7]
 [11  3 15]]


copy() method of NumPy helps to create a duplicate of the original array and you can work upon the copy without any fear of modifying the original data.
Using the copy() method lets the duplicate array owns it data and be unaffected by changes made to the former one, neither any change made in the copy affects the former.

In [23]:
# Example 2 - working
ar3 = np.array(['a','x','o'])
ar3_copy = ar3.copy()
ar3_view = ar3.view()
print('Original\n',ar3)
# change the copy
ar3_copy[2] = 4
ar3_view[1] = 'm'
print('Copy:\n',ar3_copy)
print('View:\n',ar3_view)
print('Final\n',ar3)

Original
 ['a' 'x' 'o']
Copy:
 ['a' 'x' '4']
View:
 ['a' 'm' 'o']
Final
 ['a' 'm' 'o']


Here, you get a clear example showing how copy() and view() works.
copy() created a duplicate and owned its data and hence its changes remained within its boundary.
view() created only a viewing object and any changes made to view affected the original array and vice-versa.

In [27]:
# Example 3 - how to know if an array owns its data?
print(ar3.base)
print(ar3_copy.base)
print(ar3_view.base)

None
None
['a' 'm' 'o']


Here, the attribute **<i>base** returns <i>None</i> if the array owns its data, otherwise it refers to the array object.

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sankhadeepriju/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/sankhadeepriju/numpy-array-operations


'https://jovian.ai/sankhadeepriju/numpy-array-operations'

## Function 5 - np.multiply()

This function makes arithmetic multiplication of 2 arrays of same dimension incredibly easy and fast.

In [44]:
# Example 1 - working
m = np.array([6,2,1])
n = np.array([2,1,0])
product = np.multiply(m,n)
product 

array([12,  2,  0])

The method multiply takes parameters as 2 arrays and returns the value after conducting element-wise multiplication.

In [61]:
# Example 2 - working
m = np.array([[3,4],[3,9]])
n = np.array([[5,1],[7,2]])
product1 = np.multiply(m,n)
print(product1)

[[15  4]
 [21 18]]


This shows element-wise multiplication across all dimensions.

In [49]:
# Example 3 - breaking (to illustrate when it breaks)
m = np.array([6,2,1])
n = np.array(['2',1,0])
product = np.multiply(m,n)
product 

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

Here, you can see that the second array has one <i> String </i> data and hence not possible to find a product value.

Use sum(), product() and many other similar arithmetical functions of NumPy for easy and fast calculation of multiple arrays.
Don't be confused with matmul() method where 2 arrays are treated as matrix and product is found on basis of Matrix Multiplication.

In [62]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sankhadeepriju/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/sankhadeepriju/numpy-array-operations


'https://jovian.ai/sankhadeepriju/numpy-array-operations'

## Conclusion

So, we have learned about some basic functionality and some useful methods of NumPy module.
Be innovative and answer your own questions by typing codes in Jupyter. For more about NumPy module and it's pther useful functions, Google search your query or type 'NumPy functions' or visit https://www.educba.com/introduction-to-numpy/?source=leftnav

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* More about NumPy: https://www.educba.com/introduction-to-numpy/?source=leftnav

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>